"""empty message

Revision ID: 1d5c869c9b5a
Revises: e3cd6d70efdf
Create Date: 2018-08-23 18:22:04.820789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5c869c9b5a'
down_revision = 'e3cd6d70efdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullAddressEn', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private')
    # ### end Alembic commands ###
